### PR TITLE
Feature/cluster fix

### LINKED ISSUE #35: Markers duplication in Marker Cluster Group

### PR DESCRIPTION
**Pull request by gynekolog**
Close #35

### CODE REVIEW

**Comment by gynekolog** [comment]
Pull request solve marker duplicity in clusters only. Component refactoring will be nice so I create [project card for it]( https://github.com/argo22com/garbage_map/projects/2#card-35321615).

File: src/components/LeafletCluster.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+export const LeafletCluster: React.FC<Props> = ({ markers }) => {
+  const { map } = useLeaflet();
+
+  useEffect(() => {
+    markerClusterGroup.clearLayers();
+
+    markers.map(marker => marker.addTo(markerClusterGroup));
+
+    map?.addLayer(markerClusterGroup);
```
Comment (wodCZ) [inline src/components/LeafletCluster.tsx:25]: Shouldn't there be something like `map.removeLayer` to clean-up on change?

I think this will cause memory leaks as layers are only added, not removed 🤔

Comment (gynekolog) [reply src/components/LeafletCluster.tsx:25]: No. The same layer (markerClusterGroup) but with different markers is added to the map.
I checked all map layers IDs and there are no old layers except unchanged layers.

You can check it yourself by code below to the src/components/LeafletCluster.tsx on line line 26:
```
map?.eachLayer(function(layer) {
  // @ts-ignore
  console.log(layer._leaflet_id);
});
```

**Review by wodCZ — APPROVED** [review]
